### ISSUE TITLE
Create a bank smart contract 

### ISSUE THREAD

**Issue by mbcse** [theblockchainchief/web3-hub#10]
Make a contract where a user can deposit, withdraw funds, etc like in bank. Add more functions by researching what additional things can be added apart from basic banking operations

**Comment by mbcse** [comment]
@nidz27

**Comment by nidz27** [comment]
@mbcse Thank you for creating this issue. I will start working on it.

**Comment by nidz27** [comment]
@mbcse I have made a very simple contract. But it is still not working. Like it is not returning the balance once the deposit is made. Please help me out.

**Comment by nidz27** [comment]
@mbcse Also I spotted a very minor error in your readme. I also wanted to ask you that once we fork the repo you have said in the guidelines that we need to make a new branch. What is that? Moreover you have said about the pull request but about the files that you have mentioned to be uploaded, you have not mentioned that when do we have to upload that. Is it during the pull request? Please let me know, it will help me and I can also update that in your readme.

**Comment by AbhinavXT** [comment]
Hey! @nidz27 If you are new to git and github they try this [tutorial to learn the working of git and github.](https://www.youtube.com/watch?v=RGOj5yH7evk)

Also, what are you using to develop and test smart contracts ? Did you try [remix ](https://remix.ethereum.org/) ? 
It is a web-based ethereum IDE, great for beginners.

**Comment by nidz27** [comment]
@mbcse Thank you for the tutorial. As for the smart contracts, I am using remix. The code even got compiled but it is not executing properly.

**Comment by AbhinavXT** [comment]
@nidz27 This might help you [Solidity by example](https://solidity-by-example.org/)

**Comment by belelaritra** [comment]
I want to work on this issue under JWOC.
