### ISSUE TITLE
Create an ERC721 Smart Contract

### ISSUE THREAD

**Issue by mbcse** [theblockchainchief/web3-hub#3]
Create a ERC721 Smart contract, which should be ready to modify and use by anyone. Comment should be properly added to explain what and how changes to be done. Include all features/ functions of ERC721.

**Comment by SudeepGowda55** [comment]
Hey I am working on web 3 projects. I can work on this issue.

**Comment by AnmolSirola** [comment]
@fykaa Can I work on this issue.

**Comment by fykaa** [comment]
Sure, if you want to. Send updates withing next 6days.

**Comment by AnmolSirola** [comment]
@mbcse @fykaa I have completed the assigned task and made a PR

**Comment by mbcse** [comment]
@AnmolSirola  Thanks for contributing, You can head to other issues
