### ISSUE TITLE
Design a better readme and improve contribution guidelines

### ISSUE THREAD

**Issue by mbcse** [theblockchainchief/web3-hub#31]
Add buttons, contributors list, etc in ReadMe to make it look better with all required details and also improve contribution guidelines, templates, etc.

**Comment by akashthedeveloper** [comment]
@mbcse would love to work on this issue please assign it to me

**Comment by akashthedeveloper** [comment]
@mbcse can you please specify what type of buttons you are mentioning to add and what template you are referring to?

**Comment by mbcse** [comment]
@akashthedeveloper Any template would work and any kinds of badges like how any likes on repo, prs, etc

**Comment by legendarykamal** [comment]
hi @mbcse since I dont see any activity from a long time, Please assign me to complete this one :)
